# A workflow that checks that the debug options haven't bitrotted.
name: Compile with all debug options

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  all-debug-compile-only:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.15.0-dev.864+75d0ec9c0

      - name: Enable all debug flags
        run: scripts/enable-all-debug-flags.sh

      - name: Compile the project
        run: zig build
